# To use:
#
#     pre-commit run -a
#
# Or:
#
#     pre-commit install  # (runs every time you commit in git)
#
# To update this file:
#
#     pre-commit autoupdate
#
# See https://github.com/pre-commit/pre-commit

exclude: '(^|/)third_party/'

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
    - id: check-added-large-files
    - id: check-docstring-first
    - id: check-merge-conflict
    - id: check-symlinks
    - id: check-xml
    - id: check-yaml
      args: [--allow-multiple-documents]
    - id: end-of-file-fixer
    - id: mixed-line-ending
    - id: trailing-whitespace
      exclude_types: [rst]
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v20.1.8
    hooks:
      - id: clang-format
        name: Clang Format
        args: [--style=file]
        files: \.(cpp|hpp|h|c|cc)$
  - repo: local
    hooks:
      - id: cppcheck
        name: Cppcheck
        entry: cppcheck --force --quiet --inline-suppr --error-exitcode=1 --language=c++
          "-DRCLCPP_SMART_PTR_DEFINITIONS(...)="
          "-DRCLCPP_SMART_PTR_DEFINITIONS_NOT_COPYABLE(...)="
          "-DRCLCPP_DISABLE_COPY(...)="
        language: system
        types: [c, c++]
        files: \.(cpp|hpp|h|c|cc)$
